apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-dashboard
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/Kiran-Kumar-K17/simple-k8s-node-Project.git
    targetRevision: main
    path: redis
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
    prune: true
    selfHeal: true
    syncOptions:
      - CreateNamespace=true
