apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-k8s-node-project
  name: simple-k8s-node-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-k8s-node-project
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-k8s-node-project
    spec:
      containers:
        - image: kirankumark17/simple-k8s-node-project:v.1
          name: simple-k8s-node-project
          ports:
            - containerPort: 3000
          resources: {}
status: {}
